<?php

/**
 * @file
 * local_actions.theme
 */

/**
 * Local actions preprocess.
 */
function the_strata_theme_preprocess_menu_local_action(&$variables) {
  // Are we displaying an edit form?
  if (_the_strata_theme_form_actions()) {
    $classes = &$variables['link']['#options']['attributes']['class'];
    $classes = array_filter($classes, function ($e) {
      return $e != 'button--primary';
    });
  }
}
